name: Multi-Job Workflow
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Job 1
        run: echo "This is Job 1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1 in Job 2
        run: echo "This is Job 2"
