name: CI/CD Workflow with Parallel Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout Repository code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-app:${{ github.sha }} my-docker-username/my-app:${{ github.sha }}
          docker push my-docker-username/my-app:${{ github.sha }}
