name: Matrix Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Python (matrix-based)
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Step 3: Install dependencies
      - name: Install pytest
        run: pip install pytest
      # Step 4: Run the tests
      - name: Run Python tests
        run: pytest test_script.py
