name: Format, Lint and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  format-lint-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Python (matrix-based)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Step 3: Install dependencies
      - name: Install pytest
        run: |
          pip install black pytest pytest-cov flake8
      # Step 4: Run Black (check for formatting issues)
      - name: Check code formatting with Black
        run: black . --check
      # Step 5: Run linter (flake8)
      - name: Run flake8 linter
        run: flake8 .
      # Step 6: Run tests and generate coverage
      - name: Run tests with coverage
        run: pytest --cov=script --cov-report=term-missing --junitxml=results.xml
      # Step 7: Upload test logs and coverage reports as artifacts
      - name: Upload test logs and reports
        uses: actions/upload-artifact@v3
        with:
          name: test-results-and-coverage
          path: |
            results.xml
            .coverage
