name: Test Coverage Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Python (matrix-based)
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Step 3: Install dependencies
      - name: Install pytest
        run: |
          pip install pytest pytest-cov
      # Step 4: Run the tests with coverage
      - name: Run tests and generate coverage
        run: |
          pytest --cov=script --cov-report=term-missing
      # Step 5: Upload coverage report as artifact
      - name: Save coverage report
        run: |
          pytest --cov=script --cov-report=html
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
