name: Python Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Python
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      # Step 3: Install dependencies
      - name: Install pytest
        run: pip install pytest
      # Step 4: Run the tests
      - name: Run Python tests
        run: pytest test_script.py
