name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print a message
        run: echo "Hello, this is my first GitHub Actions workflow!"
