name: Lint and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  lint-and-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3
      # Step 2: Set up Python (matrix-based)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Step 3: Install dependencies
      - name: Install pytest
        run: |
          pip install pytest pytest-cov flake8
      # Step 4: Run linter flake8
      - name: Run flake8 linter
        run: flake8 .
      # Step 5: Run tests and generate coverage
      - name: Run tests with coverage
        run: pytest --cov=script --cov-report=term-missing
